model:
  backbone: dinov2 # dinov2 or osnet
  feature_mode: cls_patchavg # cls or cls_patchavg
  pretrained: true
  lora_rank: 16
  use_lora: false
  osnet_weights: /mnt/nfs/home/st201745/weights/osnet_x1_0_market_256x128_amsgrad_ep150_stp60_lr0.0015_b64_fb10_softmax_labelsmooth_flip.pth

data:
  train: data_csv/train_records.csv
  query: data_csv/query_records.csv
  gallery: data_csv/gallery_records.csv
  num_workers: 4

sampler:
  P: 16
  K: 4

optim:
  epochs: 100
  warmup: 10
  lr: 0.001
  ce_weight: 0.0
  label_smoothing: 0.1
  triplet_weight: 1.0
  margin: 0.3
  arcface_weight: 1.0
  supcon_weight: 1.0
  max_grad_norm: 1.0

eval:
  interval: 50
  batch_size: 64

output:
  checkpoint_dir: checkpoints
  log_path: checkpoints/training_log.csv
