model:
  backbone: osnet
  feature_mode: cls_patchavg
  pretrained: true
  lora_rank: 32
  use_lora: false   # set to false for full fine-tuning
  osnet_weights: /mnt/nfs/home/st201745/weights/osnet_x1_0_market_256x128_amsgrad_ep150_stp60_lr0.0015_b64_fb10_softmax_labelsmooth_flip.pth
  # osnet_weights: /mnt/nfs/home/st201745/weights/osnet_ain_ms_m_c.pth.tar
  
data:
  train: /mnt/nfs/home/st201745/aicity_preprocessed/manifests/image_train.csv
  query: /mnt/nfs/home/st201745/aicity_preprocessed/manifests/image_query.csv
  gallery: /mnt/nfs/home/st201745/aicity_preprocessed/manifests/image_gallery.csv
  num_workers: 4

sampler:
  P: 16
  K: 4

optim:
  epochs: 300
  warmup: 10
  lr: 0.003
  ce_weight: 1.0
  label_smoothing: 0.1
  triplet_weight: 1.0
  margin: 0.3
  arcface_weight: 1.0
  supcon_weight: 1.0
  max_grad_norm: 1.0

eval:
  interval: 50
  batch_size: 64

output:
  checkpoint_dir: /mnt/nfs/home/st201745/checkpoints
  log_path: /mnt/nfs/home/st201745/checkpoints/training_log.csv
